### PR TITLE
Update Ugwu-Abel.md

### PR DESCRIPTION
**Pull request by Abel-hub0456**

### CODE REVIEW

**Comment by Abel-hub0456** [comment]
@Jaycarlx

**Comment by Jaycarlx** [comment]
You're submitting contributions to privacy policy issue? Have u created the pull request for it? Also the contend-debt.html
Create pull requests for these so i can merge

**Comment by Abel-hub0456** [comment]
I just created a pull request for Privacy Policy Page.

**Comment by Jaycarlx** [comment]
Seen. Make sure you push the files for contend-debt too

**Comment by Jaycarlx** [comment]
Merged

**Pull request merged**
