### PR TITLE
Debtors models

### PR DESCRIPTION
**Pull request by sylviaokwu**

### CODE REVIEW

**Comment by TolulopeJoel** [comment]
Suggestion: I don't think there is a need for a id field because Django comes with an inbuilt id field and there is also some unused imported packages in your code, btw suggestion 🤲.

**Comment by Ezrahel** [comment]
Tolu, I suppose there is a need to generate an id for each debtor posted by the school according to what was discussed in the meeting. If you know a way we can display the id generated by django on each debtor so as to be visible to other schools, then we make corrections.

**Comment by TolulopeJoel** [comment]
> Tolu, I suppose there is a need to generate an id for each debtor posted by the school according to what was discussed in the meeting. If you know a way we can display the id generated by django on each debtor so as to be visible to other schools, then we make corrections.

Definitely there is a need to generate an id, but django does that for us so we don't need to, unless you want to override the way the id field functions, and according to the code she pushed it isn't overriding the intial I'd Django creates for us.

**Comment by TolulopeJoel** [comment]
> Tolu, I suppose there is a need to generate an id for each debtor posted by the school according to what was discussed in the meeting. If you know a way we can display the id generated by django on each debtor so as to be visible to other schools, then we make corrections.

You will call the id just the way you call any other field, just imagine you created the id field (but you didn't because Django has done that) and you're calling it

**Comment by Ezrahel** [comment]
write the syntax so that she can edit and make another pull request

**Pull request merged**
